import { NextRequest, NextResponse } from "next/server";

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || "";
const TG = `https://api.telegram.org/bot${BOT_TOKEN}`;

// In-memory conversation state: chatId → keyword awaiting role selection
const pending = new Map<number, string>();

// ── Telegram helpers ────────────────────────────────────────────────────

async function tgSend(chatId: number, text: string, opts?: Record<string, unknown>) {
    await fetch(`${TG}/sendMessage`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chat_id: chatId, text, parse_mode: "Markdown", ...opts }),
    });
}

async function tgEdit(chatId: number, messageId: number, text: string) {
    await fetch(`${TG}/editMessageText`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chat_id: chatId, message_id: messageId, text, parse_mode: "Markdown" }),
    });
}

async function answerCallback(callbackId: string) {
    await fetch(`${TG}/answerCallbackQuery`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ callback_query_id: callbackId }),
    });
}

// ── Role keyboard ───────────────────────────────────────────────────────

const ROLE_KEYBOARD = {
    inline_keyboard: [
        [
            { text: "Content Creator", callback_data: "role:content-creator" },
            { text: "Marketer", callback_data: "role:marketing-team" },
        ],
        [
            { text: "Trend Analyst", callback_data: "role:general-user" },
            { text: "Platform Executive", callback_data: "role:platform-moderator" },
        ],
    ],
};

const ROLE_LABELS: Record<string, string> = {
    "content-creator": "Content Creator",
    "marketing-team": "Marketer",
    "general-user": "Trend Analyst",
    "platform-moderator": "Platform Executive",
};

// ── Pipeline call ───────────────────────────────────────────────────────

async function analyzeTrend(keyword: string, userRole: string) {
    // Call internal full pipeline
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || process.env.VERCEL_URL
        ? `https://${process.env.VERCEL_URL}`
        : "http://localhost:3000";

    const res = await fetch(`${baseUrl}/api/pipeline/full`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ keyword, userRole, platforms: [] }),
    });

    if (!res.ok) throw new Error(`Pipeline failed: ${res.status}`);
    return res.json();
}

// ── Format result ───────────────────────────────────────────────────────

function formatResult(data: Record<string, unknown>, keyword: string, role: string): string {
    const lines: string[] = [];

    // Header
    lines.push(`*TREND PRISM* — Decline Prediction Report`);
    lines.push(`Keyword: *${escMd(keyword)}*`);
    lines.push(`View: ${ROLE_LABELS[role] || role}`);
    lines.push("");

    // Verdict
    const verdict = data.verdict as Record<string, unknown> | undefined;
    if (verdict?.verdict) {
        const v = String(verdict.verdict).toUpperCase();
        const emoji = v === "NOT ANYTIME SOON" ? "\u{1F7E2}" : v === "DECLINING" ? "\u{1F534}" : "\u{1F7E1}";
        lines.push(`${emoji} *Verdict: ${escMd(String(verdict.verdict))}*`);
        if (verdict.confidence) lines.push(`Confidence: ${verdict.confidence}%`);
        if (verdict.riskLevel) lines.push(`Risk Level: ${escMd(String(verdict.riskLevel))}`);
        lines.push("");
    }

    // About / AI Interpretation
    const bm = data.basicMetrics as Record<string, unknown> | undefined;
    const adv = data.advancedInferences as Record<string, unknown> | undefined;
    const about = bm?.llmInterpretation || adv?.llmAnalysis || verdict?.summary || data.summary;
    if (about) {
        lines.push(`*About*`);
        lines.push(escMd(String(about)));
        lines.push("");
    }

    // Deep Analysis (if different from about)
    const deepAnalysis = adv?.llmAnalysis && verdict?.summary && adv.llmAnalysis !== verdict.summary
        ? String(adv.llmAnalysis)
        : null;
    if (deepAnalysis && deepAnalysis !== String(about)) {
        lines.push(`*AI Deep Analysis*`);
        lines.push(escMd(deepAnalysis));
        lines.push("");
    }

    // Verdict summary
    if (verdict?.summary && String(verdict.summary) !== String(about) && String(verdict.summary) !== deepAnalysis) {
        lines.push(`*Verdict Summary*`);
        lines.push(escMd(String(verdict.summary)));
        lines.push("");
    }

    lines.push(`_Generated by TREND PRISM V2.0_`);
    lines.push(`_Multi-Model AI Pipeline_`);

    return lines.join("\n");
}

function escMd(s: string): string {
    // Escape markdown v1 special chars (except * and _ which we use for formatting)
    return s.replace(/([`\[\]])/g, "\\$1");
}

// ── Webhook handler ─────────────────────────────────────────────────────

async function processUpdate(update: Record<string, unknown>) {
    // Handle /start
    const message = update.message as Record<string, unknown> | undefined;
    if (message) {
        const chatId = (message.chat as Record<string, unknown>).id as number;
        const text = (message.text as string || "").trim();

        if (text === "/start") {
            pending.delete(chatId);
            await tgSend(chatId,
                `*Welcome to TREND PRISM Bot!*\n\n` +
                `I predict when and why social media trends begin to decline.\n\n` +
                `Send me any *trend keyword* (e.g. "AI agents", "Squid Game", "ChatGPT") and I'll analyze it for you.`
            );
            return;
        }

        if (text.startsWith("/")) return; // ignore unknown commands

        // Treat as keyword — store and ask for role
        pending.set(chatId, text);
        await tgSend(chatId,
            `Analyzing *${escMd(text)}* — which perspective do you want?`,
            { reply_markup: ROLE_KEYBOARD }
        );
        return;
    }

    // Handle role selection callback
    const callback = update.callback_query as Record<string, unknown> | undefined;
    if (callback) {
        const cbData = callback.data as string;
        const cbMessage = callback.message as Record<string, unknown>;
        const chatId = (cbMessage.chat as Record<string, unknown>).id as number;
        const messageId = cbMessage.message_id as number;

        await answerCallback(callback.id as string);

        if (!cbData.startsWith("role:")) return;
        const role = cbData.replace("role:", "");
        const keyword = pending.get(chatId);

        if (!keyword) {
            await tgSend(chatId, "Please send me a trend keyword first!");
            return;
        }

        pending.delete(chatId);

        // Show loading message
        await tgEdit(chatId, messageId,
            `Analyzing *${escMd(keyword)}* as ${ROLE_LABELS[role] || role}...\n\n_This takes 15-30 seconds — running multi-model AI pipeline..._`
        );

        try {
            const data = await analyzeTrend(keyword, role);
            const result = formatResult(data, keyword, role);
            await tgSend(chatId, result);
        } catch (err) {
            console.error("Telegram pipeline error:", err);
            await tgSend(chatId,
                `Sorry, analysis failed for "${escMd(keyword)}". The pipeline may be rate-limited — try again in a moment.`
            );
        }
    }
}

// POST — Telegram webhook
export async function POST(req: NextRequest) {
    try {
        const update = await req.json();
        // Process asynchronously so Telegram doesn't timeout
        processUpdate(update).catch(err => console.error("Telegram update error:", err));
        return NextResponse.json({ ok: true });
    } catch {
        return NextResponse.json({ ok: true });
    }
}

// GET — Health check
export async function GET() {
    return NextResponse.json({ status: "Telegram webhook active" });
}
